"""Testing subagent.

Maps declared API endpoints (Flask or FastAPI style, found anywhere in the
repo) against what the existing test suite actually exercises through an
HTTP test client, reports the coverage gap, and auto-generates pytest stubs
for every uncovered endpoint.

Not every real project is a web API, and not every project tests through
HTTP calls (some, like model-level unittest suites, test the underlying
functions directly). So DevPilot also computes a second, always-available
metric -- how many of the codebase's functions are referenced by name
anywhere in the test suite -- and reports whichever is meaningful.
"""
import os
import re

from devpilot.scanutil import find_routes, find_client_calls, find_app_entrypoint, find_route_prefixes, iter_py_files, normalize_path, read_text, module_summary

STUB_TEMPLATE = '''

def test_{name}():
    """Auto-generated by DevPilot's testing subagent -- fill in real assertions."""
    resp = client.{method}("{path}")
    assert resp.status_code in (200, 404, 422)  # TODO: narrow this down
'''


def _build_stub_header(project_path):
    """Best-effort, framework-agnostic import block: try to locate the real
    app instance; if DevPilot can't find one, skip cleanly instead of
    crashing test collection with a NameError."""
    entry = find_app_entrypoint(project_path)
    lines = ["import pytest", ""]
    if entry and entry["kind"] == "instance":
        lines += [
            "app = None",
            f"try:\n    from {entry['module']} import {entry['var']} as app\nexcept Exception:\n    pass",
        ]
    elif entry and entry["kind"] == "factory":
        lines += [
            "app = None",
            f"try:\n    from {entry['module']} import create_app\n    app = create_app()\nexcept Exception:\n    pass",
        ]
    else:
        lines += ["app = None"]

    lines += [
        "if app is None:",
        "    pytest.skip('DevPilot could not automatically locate the app instance -- wire up the import above by hand', allow_module_level=True)",
        "",
        "try:",
        "    from fastapi.testclient import TestClient",
        "    client = TestClient(app)",
        "except Exception:",
        "    client = app.test_client()",
    ]
    return "\n".join(lines)


def _collect_routes(project_path):
    prefixes = find_route_prefixes(project_path)
    routes = []
    for full, rel in iter_py_files(project_path, skip_tests=True):
        source = read_text(full)
        module_basename = os.path.splitext(os.path.basename(rel))[0]
        prefix = prefixes.get(module_basename, "")
        for r in find_routes(source):
            path = r["path"] if r["path"].startswith("/") else "/" + r["path"]
            full_path = (prefix.rstrip("/") + path) if prefix else path
            full_path = full_path if full_path.startswith("/") else "/" + full_path
            routes.append({"method": r["method"], "path": full_path or "/", "source_file": rel, "function": r["function"]})
    return routes


def _collect_test_files(project_path):
    test_files = []
    for full, rel in iter_py_files(project_path):
        base = os.path.basename(rel)
        if base.startswith("test_") or base.endswith("_test.py") or base in ("tests.py",) or "/tests/" in rel.replace(os.sep, "/") or rel.replace(os.sep, "/").startswith("tests/"):
            test_files.append(full)
    return test_files


def _endpoint_coverage(routes, test_files):
    covered = set()
    for f in test_files:
        source = read_text(f)
        for method, path in find_client_calls(source):
            covered.add((method, normalize_path(path)))

    uncovered = []
    for r in routes:
        key = (r["method"], normalize_path(r["path"]))
        if key not in covered:
            uncovered.append(r)
    total = len(routes)
    covered_count = total - len(uncovered)
    return covered_count, uncovered


def _function_level_coverage(project_path, test_files):
    """Fallback metric: of the functions defined in non-test source files,
    how many are referenced (called) anywhere in the test suite by name?"""
    defined = set()
    for full, rel in iter_py_files(project_path, skip_tests=True):
        summary = module_summary(full)
        for name in summary["functions"]:
            if not name.startswith("_"):
                defined.add(name)

    test_source = "\n".join(read_text(f) for f in test_files)
    referenced = {name for name in defined if re.search(r"\b" + re.escape(name) + r"\s*\(", test_source)}

    total = len(defined)
    pct = round(100 * len(referenced) / total, 1) if total else 0.0
    return {"total_functions": total, "referenced_functions": len(referenced), "pct": pct}


def run(project_path):
    routes = _collect_routes(project_path)
    test_files = _collect_test_files(project_path)

    generated_test_source = None
    generated_test_file = "tests/test_devpilot_generated.py"

    any_client_calls = any(find_client_calls(read_text(f)) for f in test_files)

    if routes:
        covered_count, uncovered = _endpoint_coverage(routes, test_files)
        total = len(routes)
        coverage_pct = round(100 * covered_count / total, 1) if total else 100.0

        stub_lines = [_build_stub_header(project_path)]
        stub_name_to_endpoint = {}
        for ep in uncovered:
            safe_name = re.sub(r"[^a-zA-Z0-9]+", "_", f"{ep['method']}_{ep['path']}").strip("_").lower()
            example_path = re.sub(r"[<{][^>}]+[>}]", "1", ep["path"])
            stub_lines.append(STUB_TEMPLATE.format(name=safe_name, method=ep["method"], path=example_path))
            stub_name_to_endpoint[f"test_{safe_name}"] = ep
        if uncovered:
            generated_test_source = "\n".join(stub_lines) + "\n"

        result = {
            "agent": "testing",
            "coverage_kind": "http_endpoint",
            "total_endpoints": total,
            "covered_endpoints": covered_count,
            "uncovered_endpoints": uncovered,
            "coverage_pct": coverage_pct,
            "stub_name_to_endpoint": stub_name_to_endpoint,
        }
    else:
        result = {
            "agent": "testing",
            "coverage_kind": "none_detected",
            "total_endpoints": 0,
            "covered_endpoints": 0,
            "uncovered_endpoints": [],
            "coverage_pct": None,
            "stub_name_to_endpoint": {},
        }

    func_cov = _function_level_coverage(project_path, test_files)
    result["function_coverage"] = func_cov
    result["test_files_found"] = len(test_files)
    result["generated_test_file"] = generated_test_file
    result["generated_test_source"] = generated_test_source

    # Headline number: HTTP endpoint coverage when the project actually tests
    # through an HTTP client -- but a project can have real routes AND a real
    # test suite that simply doesn't drive them over HTTP (e.g. it tests the
    # underlying model/service functions directly). In that case "0% endpoint
    # coverage" would be a misleading headline about a category difference,
    # not a real gap, so fall back to the function-reference metric instead.
    if result["coverage_kind"] == "http_endpoint" and any_client_calls:
        result["headline_coverage_pct"] = result["coverage_pct"]
        result["headline_label"] = "endpoint test coverage"
    elif result["coverage_kind"] == "http_endpoint":
        result["headline_coverage_pct"] = func_cov["pct"]
        result["headline_label"] = "functions referenced in tests (no HTTP-client tests detected)"
    else:
        result["headline_coverage_pct"] = func_cov["pct"]
        result["headline_label"] = "functions referenced in tests"

    return result
